dcms/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from office.views import DashboardView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role")),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^notifications/', include("notifications.urls", namespace="notifications")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^$', DashboardView.as_view(), name='dashboard'),


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = ([
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/users/login/'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'Password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'Password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'Password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^firstlogin/$', views.firstlogin, name='firstlogin'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.my_profile, name='profile'),

    
    
])

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User, Group
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from office.models import Office


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	email_confirmed = models.BooleanField(default=False)
	name = models.CharField(max_length=30, blank=True)
	phoneno = models.CharField(max_length=30, blank=True)
	assign_date = models.DateField(null=True, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	photo = models.ImageField(null=True, blank=True)
	bio = models.TextField(null=True, blank=True)
	def __str__(self):
		return str(self.user)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserDetailsForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('password1', 'password2',)

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .imagecropper import PhotoForm
from django.shortcuts import render
from django.contrib.auth.models import User

from django.contrib.auth import login, authenticate
from django.views.generic import View
from .tokens import account_activation_token
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from .models import Profile
from .forms import UserDetailsForm
from userrole.forms import UserRoleForm
from userrole.mixins import LoginRequiredMixin, SuperAdminMixin, CreateView, UpdateView, DeleteView
from userrole.models import UserRole as Role, UserRole

from django.shortcuts import redirect
from django.urls import reverse_lazy

class UserRoleView(object):
    model = UserRole
    success_url = reverse_lazy('role:user-role-list')
    form_class = UserRoleForm         



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None


    if user is not None and account_activation_token.check_token(user, token):

        profile = get_object_or_404(Profile, user=uid)
        photoform = PhotoForm(request.POST or None, instance=profile)
        userform = UserDetailsForm()


        return render(request, 'profiledetails.html', {'uid': uidb64, 'photoform':photoform, 'userform':userform})
    else:
    	return redirect('users:login')

    		#return redirect('question_detail', pk=question.pk)
    	#return redirect('supa:listoffice')





def firstlogin(request, *args, **kwargs):

    if request.method=='POST':

    	password1 = request.POST.get('password1')
    	password2 = request.POST.get('password2')

    	if password2 == password1:
        	usrid = request.POST.get('uidb64')
        	uid = force_text(urlsafe_base64_decode(usrid))
        	user = User.objects.get(pk=uid)
        	user.profile.email_confirmed = True
        	user.set_password(password2)
        	user.is_active = True
        	user.save()
                office = UserRole.get_office(uid)
                profile = get_object_or_404(Profile, user=uid)
            	user1 = authenticate(username=user.username, password=password2)
            	form = PhotoForm(request.POST, request.FILES, instance=profile)

        	if form.is_valid():
        		form.save()

        	login(request, user1)

        	return redirect('office:office-dashboard', pk=office.id)
    	return redirect('error')

def my_profile(request, pk=None):
    if not pk or pk =='0':
        profile, created = Profile.objects.get_or_create(user=request.user)
        roles = request.user.user_roles.all()
    else:
        profile, created = Profile.objects.get_or_create(user__id=pk)
        roles = profile.user.user_roles.all()

    return render(request, 'users/profile.html', {'obj': profile, 'roles': roles})

users/templates/Password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
    
<head>
        <title>Supa Admin</title><meta charset="UTF-8" />
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/matrix-login.css' %}" />
        <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    </head>
    <body>

      <div class="span12" style="color:white;">
        <div class="widget-box">
          <div class="widget-content">
            <div class="error_ex">
              <h1>Password Sucessfully Changed</h1>
    <p>
    Your password has been set. You may go ahead and <a style="color:aqua;" href="{% url 'users:login' %}">sign in</a> now.
  </p>
  <br>
  <br>
  <br>
              <a class="btn btn-warning btn-big" href="{% url 'login' %}">Back to login</a> </div>
          </div>
        </div>
      </div>

         <script src="{% static 'js/jquery.min.js' %}"></script>  
        <script src="{% static 'js/matrix.login.js' %}"></script> 
    </body>

</html>





















 

users/templates/Password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
    
<head>
        <title>Supa Admin</title><meta charset="UTF-8" />
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/matrix-login.css' %}" />
        <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    </head>
    <body>


{% if validlink %}
<div id="loginbox">  
              {% if form.errors %}
            <div class="alert alert-error">
  
              
              <strong>Error!</strong> <ul class='form-errors'>
                
                     {{ form.new_password2.errors }}
               
            </ul>
            </div>              
                {% endif %}

               
                 <form id="loginform" class="form-vertical" method="post">
                 <p class="normal_text">Enter your new Password.</p>
            {% csrf_token %}
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_ly"><i class="icon-lock"></i></span><input type="password" id="id_password" required name="new_password1" placeholder="Password" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_ly"><i class="icon-lock"></i></span><input type="password" id="id_password" required name="new_password2" placeholder="Re-Enter Password" />
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                   
                    <span class="pull-right"><button style="color: white;" type="submit" class="btn btn-success" />Change Password</span>
                </div>
               

            </form>
    </div>


  {% else %}
   <div class="span12" style="color:white;">
        <div class="widget-box">
          <div class="widget-content">
            <div class="error_ex">
              <h1>Alert !!! </h1>
    <p>
    The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
  </p>
  <br>
  <br>
  <br>
              <a class="btn btn-warning btn-big" href="{% url 'users:login' %}">Back to login</a> </div>
          </div>
        </div>
      </div>
      



      
  {% endif %}
     

         <script src="{% static 'js/jquery.min.js' %}"></script>  
        <script src="{% static 'js/matrix.login.js' %}"></script> 
    </body>

</html>

users/templates/Password_reset_done.html
<!DOCTYPE html>
<html lang="en">
    
<head>
        <title>Supa Admin</title><meta charset="UTF-8" />
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/matrix-login.css' %}" />
        <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    </head>
    <body>

      <div class="span12" style="color:white;">
        <div class="widget-box">
          <div class="widget-content">
            <div class="error_ex">
              <h1>Confirmation Sent</h1>
             <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
  <br>
  <br>
  <br>
              <a class="btn btn-warning btn-big" href="{% url 'users:login' %}">Back to login</a> </div>
          </div>
        </div>
      </div>

         <script src="{% static 'js/jquery.min.js' %}"></script>  
        <script src="{% static 'js/matrix.login.js' %}"></script> 
    </body>

</html>

users/templates/Password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
    
<head>
        <title>Supa Admin</title><meta charset="UTF-8" />
        {% load staticfiles %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/matrix-login.css' %}" />
        <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

    </head>
    <body>

        <div id="loginbox">  

           

            <form id="loginform" class="form-vertical" method="post">
            {% csrf_token %}
             {% if form.non_field_errors %}
            <div class="alert alert-error">
  
              
              <strong>Error!</strong> <ul class='form-errors'>
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
            </div>              
                {% endif %}

				 <div class="control-group normal_text">  <img style="margin: 10px;" src="http://naxa.com.np/appadmin/application/logo.png" height="45px" width="200px"></div>

                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_lg"><i class="icon-user"> </i></span><input type="text" id="id_username" required name="username"placeholder="Username" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_ly"><i class="icon-lock"></i></span><input type="password" id="id_password" required name="password"placeholder="Password" />
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link btn btn-info" id="to-recover">Forgot password?</a></span>
                    <span class="pull-right"><button type="submit" class="btn btn-success" />Login</span>
                </div>
               

            </form>



            <form id="recoverform" action="{% url 'users:password_reset' %}" class="form-vertical" method="post">
                {% csrf_token %}
				<p class="normal_text">Enter your e-mail address below and we will send you instructions how to recover a password.</p>
				
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on bg_lo"><i class="icon-envelope"></i></span><input type="text" name="email" required placeholder="E-mail address" />
                        </div>
                    </div>
               
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link btn btn-success" id="to-login">&laquo; Back to login</a></span>
                    <span class="pull-right"><a><button type="submit" class="btn btn-success" />Reecover</a></span>
                </div>
            </form>
        </div>
        <script src="{% static 'js/jquery.min.js' %}"></script>  
        <script src="{% static 'js/matrix.login.js' %}"></script> 
    </body>

</html>

users/templates/profiledetails.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Matrix Admin</title>
{% load staticfiles %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}" />
<link rel="stylesheet" href="{% static 'css/matrix-style.css' %}" />
<link rel="stylesheet" href="{% static 'css/matrix-media.css' %}" />

<link rel="stylesheet" href="{% static 'css/imgcropper.css' %}" />
<link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="{% static 'js/imgcropper.js' %}"></script> 

</head>
<body>

<!--Header-part-->
<script type="text/javascript">

    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_photo").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);

        
      });

    });
  
</script>

  
  <div class="container-fluid">
  

    <div class="row-fluid">
     <center>
        <div class="widget-box" style="width: 600px;">
          <div class="widget-title"> <span class="icon"> <i class="icon-pencil"></i> </span>
            <h5>Welcome, User</h5>
          </div>
          <div class="widget-content nopadding">

            <form id="form-wizard" class="form-horizontal" enctype="multipart/form-data" action = "{% url 'users:firstlogin' %}" method="post">
            {% csrf_token %}
              <div id="form-wizard-1" class="step">
                <h5>Please set your password.</h5>
                <div class="control-group">
                {{ userform.password1.errors }}
                  <label class="control-label">Password</label>
                  <div class="controls">
                   {{ userform.password1 }}
                  </div>
                </div>
                <div class="control-group">
                {{ userform.password1.errors }}
                  <label class="control-label">Confirm Password</label>
                  <div class="controls">
                    {{ userform.password2 }}
                  </div>
                </div>

         
              </div>
              <div id="form-wizard-2" class="step">







                <div class="control-group">
                 {{ photoform.name.errors }}
                  <label class="control-label">{{ photoform.name.label_tag }}</label>
                  <div class="controls">
                    {{ photoform.name }}
                  </div>
                </div>

                <div class="control-group">
                 {{ photoform.phoneno.errors }}
                  <label class="control-label">{{ photoform.phoneno.label_tag }}</label>
                  <div class="controls">
                    {{ photoform.phoneno }}
                  </div>
                </div>

                <div class="control-group">
                 {{ photoform.photo.errors }}
                  <label class="control-label">{{ photoform.photo.label_tag }}</label>
                  <div class="controls">
                    {{ photoform.photo }}
                  </div>
                </div>


             
                    {{ photoform.x }}
                
                    {{ photoform.y }}
                 
                    {{ photoform.width }}
                 
                    {{ photoform.height }}
                  




              </div>


              <div class="form-actions">
              <input type="hidden" name="uidb64" value="{{ uid }}">
                <input id="back" class="btn btn-primary" type="reset" value="Back" />
                <input id="next" class="btn btn-primary" type="submit" value="Next" />
                <div id="status"></div>
              </div>
              <div id="submitted"></div>


            </form>
          </div>
        </div>
      </div>





        <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload" data-dismiss="modal">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>










</center>
  </div>


<script src="{% static 'js/jquery.ui.custom.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<!-- <script src="{% static 'js/jquery.validate.js' %}"></script>  -->
<script src="{% static 'js/jquery.wizard.js' %}"></script> 
<script src="{% static 'js/matrix.js' %}"></script> 

<script src="{% static 'js/matrix.wizard.js' %}"></script>
</body>
</html>