dcms/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from office.views import DashboardView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role")),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^notifications/', include("notifications.urls", namespace="notifications")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^$', DashboardView.as_view(), name='dashboard'),


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

office/urls.py
from django.conf.urls import url


from office.views import  OfficeAddMunicipilaty, OfficeAddProject, ProjectUpdate, MunicipalityUpdate, OfficeDetailView, \
    OfficeUserView, OfficeBudgetUpdateView

app_name = 'office'

from office.views import OfficeCreateView, AllProjectDashboard, OfficeListView, OfficeUpdateView, OfficeDeleteView, DashboardView,\
    OfficeAddOfficeHeadView, OfficeAddInfoofficerView, Monthly, OfficeDashboard, DistrictDashboard, ProfileDetailView, ProfileUpdateView, OfficeKaryakramList, DeactivateUserView



urlpatterns = [

    url(r'^office/create/$', OfficeCreateView.as_view(), name='office-add'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/$', OfficeDashboard.as_view(), name='office-dashboard'),
    url(r'^office/detail/(?P<pk>[0-9]+)/$', OfficeDetailView.as_view(), name='office-detail'),
    url(r'^office/users/(?P<pk>[0-9]+)/$', OfficeUserView.as_view(), name='office-users'),

    url(r'^district/dashbaord/(?P<pk>[0-9]+)/$', DistrictDashboard.as_view(), name='district-dashboard'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/karyakramlist/$', OfficeKaryakramList.as_view(), name='office-karyakram-list'),
    url(r'^office/update/(?P<pk>[0-9]+)/$', OfficeUpdateView.as_view(), name='office-update'),
    url(r'^office/delete/(?P<pk>[0-9]+)/$', OfficeDeleteView.as_view(), name='office-delete'),
    url(r'^office/list/$', OfficeListView.as_view(), name='office-list'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addofficehead/$', OfficeAddOfficeHeadView.as_view(), name='office-add-office-head'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addinfoofficer/$', OfficeAddInfoofficerView.as_view(), name='office-add-info-officer'),
    #url(r'^office/(?P<pk>[0-9]+)/addtype/$', OfficeAddUserView.as_view(), name='office-addtype'),
    url(r'^office/(?P<pk>[0-9]+)/addmunicipality/$', OfficeAddMunicipilaty.as_view(), name='office-add-municipilaty'),
    url(r'^office/(?P<pk>[0-9]+)/addproject/$', OfficeAddProject.as_view(), name='office-add-project'),
    url(r'^office/(?P<pk>[0-9]+)/updateproject/$', ProjectUpdate.as_view(), name='office-update-project'),
    url(r'^office/(?P<pk>[0-9]+)/updatemunicipality/$', MunicipalityUpdate.as_view(), name='office-update-municipality'),
    
    url(r'^office/addbudget/(?P<pk>[0-9]+)/$', OfficeBudgetUpdateView.as_view(), name='office-budget-update'),
    url(r'^deactivate_user/$', ProfileUpdateView.as_view(), name='deactivate-users'),
    url(r'^office/users/profile_update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^office/users/profile_detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='profile-detail'),
    url(r'^office/monthly/$', Monthly.as_view(), name='monthly-report'),
    url(r'^allprojects/$', AllProjectDashboard.as_view(), name='all-projects'),
    

        ]

reports/urls.py
from django.conf.urls import url


from .views import KaryakramCreateView, KaryakramUpdateView, LakxyaCreateView, PragatiCreateView, KaryakramListView, \
    ReportView, KaryakramControlList, YearlyControlList, FirstControlList, SecondControlList, ChildKaryakramCreateView, \
    OfficeSettings, FilesSubmitted, MonthlyControlList, MonthlyProgressList, MonthlyProgressDetail, MonthlyProgressCreateView

app_name = 'reports'

urlpatterns = [
    url(r'^karyakram/list/(?P<office>[0-9]+)/$', KaryakramListView.as_view(), name='karyakram-list'),
    url(r'^office/settings/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', OfficeSettings.as_view(), name='office-settings'),
    url(r'^karyakram/controllist/(?P<office>[0-9]+)/$', KaryakramControlList.as_view(), name='karyakram-control-list'),
    url(r'^karyakram/yearlycontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', YearlyControlList.as_view(), name='yearly-control-list'),
    url(r'^karyakram/firstcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', FirstControlList.as_view(), name='first-control-list'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', SecondControlList.as_view(), name='second-control-list'),
    url(r'^karyakram/create/(?P<office>[0-9]+)/$', KaryakramCreateView.as_view(), name='karyakram-add'),
    url(r'^karyakram/create/child/(?P<office>[0-9]+)/(?P<karyakram>[0-9]+)/$', ChildKaryakramCreateView.as_view(), name='karyakram-add-child'),
    url(r'^list/(?P<office>[0-9]+)/(?P<awadhi>[0-9]+)/$', ReportView.as_view(), name='reports'),
    url(r'^karyakram/update/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', KaryakramUpdateView.as_view(), name='karyakram-update'),
    url(r'^karyakram/addlaksya/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', LakxyaCreateView.as_view(), name='add-lakxya'),
    url(r'^karyakram/addpragati/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', PragatiCreateView.as_view(), name='add-pragati'),
    url(r'^karyakram/filessubmited/(?P<office>[0-9]+)/$', FilesSubmitted.as_view(), name='files-submited'),
    url(r'^karyakram/monthlylist/(?P<office>[0-9]+)/$', MonthlyControlList.as_view(), name='monthly-control-list'),
    url(r'^karyakram/monthlyallprogresslist/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/$', MonthlyProgressList.as_view(), name='monthly-all-progress-list'),
    url(r'^karyakram/addmonthlypragati/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<month_id>[0-9]+)/$', MonthlyProgressCreateView.as_view(), name='add-monthly-pragati'),
    url(r'^karyakram/monthlyprogressdetail/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/$', MonthlyProgressDetail.as_view(), name='monthly-progress-detail'),    

        ]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = ([
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/users/login/'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'Password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'Password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'Password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^firstlogin/$', views.firstlogin, name='firstlogin'),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.my_profile, name='profile'),

    
    
])

office/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Ministry(models.Model):
	name = models.CharField(verbose_name="नाम", max_length=255)

	def __unicode__(self):
		return u'%s'%(self.name)

class Department(models.Model):
	ministry = models.ForeignKey(Ministry, verbose_name="मन्त्रालय", related_name="department", on_delete=models.CASCADE)
	name = models.CharField(verbose_name="नाम", max_length=255)

	def __unicode__(self):
		return u'%s'%(self.ministry) + " -- " + u'%s'%(self.name)

class District(models.Model):
	district = models.CharField(verbose_name="जिल्ला", max_length=255)
	
	def __unicode__(self):
		return u'%s'%(self.district)


class Office(models.Model):
	name = models.CharField(verbose_name="नाम", max_length=255)
	address = models.CharField(verbose_name="ठेगाना", max_length=255, blank=True)
	district = models.ManyToManyField(District, verbose_name="जिल्ला", related_name="office")
	email = models.CharField(verbose_name="इमेल", max_length=255, blank=True)
	phone = models.CharField(verbose_name="फोन", max_length=255, blank=True)
	fax = models.CharField(verbose_name="फ्याकस", max_length=255, blank=True)
	office_time = models.CharField(verbose_name="कार्यालय समय", max_length=255, blank=True)
	image = models.ImageField(verbose_name="तस्बिर", upload_to='ompimage', null=True, blank=True)
	department = models.ForeignKey(Department, verbose_name="बिभाग", on_delete=models.CASCADE)
	is_municipality = models.BooleanField(verbose_name="नगरपालिका", default=False)
	is_project = models.BooleanField(verbose_name="परियोजना", default=False)
	# office_setting = models.ForeignKey(OfficeSetting, related_name="office_setting", on_delete=models.CASCADE)
	def __unicode__(self):
		return u'%s'%(self.name)

	@property
	def detail(self):
		if self.is_municipality:
			return self.municipality_detail
		elif self.is_project:
			return self.project_detail
		return None

	def get_active_fiscal_year(self):
		return self.settings


class ProjectDetail(models.Model):
	project_time = models.CharField(verbose_name="परियोजनाको समय", max_length=30)
	budget = models.CharField(verbose_name="बजेट", max_length=30)
	objective = models.TextField(verbose_name="उद्देस्य", blank=True)
	chief_eng = models.CharField(verbose_name="बरिस्ठ  इन्जिनीयर", max_length=30, blank=True)
	engineers = models.TextField(verbose_name=" इन्जिनीयरहरु", blank=True)
	office = models.OneToOneField(Office,verbose_name="कार्यालय", related_name="project_detail", on_delete=models.CASCADE)

	def __unicode__(self):
		return u'%s'%(self.office.name)


class MunicipalityDetail(models.Model):
	kendra = models.CharField(verbose_name="केन्द्र", max_length=30)
	area = models.CharField(verbose_name="एरिया", max_length=30)
	no_of_wards = models.TextField(verbose_name="वडाहरु को संख्या", blank=True)
	population = models.CharField(verbose_name="जनसंख्या", max_length=30, blank=True)
	activities = models.TextField(verbose_name="कृयाकलापहरु", blank=True)
	mayor_name = models.CharField(verbose_name="मयेर/अध्यक्षको नाम", max_length=30)
	mayor_phone_no = models.CharField(verbose_name="मयेर/अध्यक्षको फोन", max_length=30)
	mayor_address = models.CharField(verbose_name="मयेर/अध्यक्षको ठेगाना ", max_length=30, blank=True)
	sub_mayor_name = models.CharField(verbose_name="उप-मयेर/अध्यक्षको नाम", max_length=30)
	sub_mayor_phone_no = models.CharField(verbose_name="उप-मयेर/अध्यक्षको फोन", max_length=30)
	sub_mayor_address = models.CharField(verbose_name="उप-मयेर/अध्यक्षको ठेगाना ", max_length=30, blank=True)
	ward_chief_details = models.TextField(verbose_name="वडा प्रमुखको विवरण ", blank=True)
	office = models.OneToOneField(Office,verbose_name="कार्यालय", related_name="municipality_detail", on_delete=models.CASCADE)
	# is_municipality = models.BooleanField(default=True)

	def __unicode__(self):
		return u'%s'%(self.office.name)

# class OfficeSetting(models.Model):
# 	fiscalyear = models.ForeignKey(FiscalYear, verbose_name="", max_length=90, on_delete=models.CASCADE)
# 	office = models.OneToOneField(Office, verbose_name="", on_delete=models.CASCADE)
# 	def __unicode__(self):
# 		return u'%s'%(self.office.id) + "--" + u'%s'%(self.fiscalyear)

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User, Group
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.db import models
from office.models import Office


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	email_confirmed = models.BooleanField(default=False)
	name = models.CharField(max_length=30, blank=True)
	phoneno = models.CharField(max_length=30, blank=True)
	assign_date = models.DateField(null=True, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	photo = models.ImageField(null=True, blank=True)
	bio = models.TextField(null=True, blank=True)
	def __str__(self):
		return str(self.user)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

office/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from models import Office, ProjectDetail, MunicipalityDetail
from django.contrib.auth.models import User
from reports.models import OfficeBudget
from users.models import Profile

class OfficeForm(forms.ModelForm):
    class Meta:
        model = Office
        exclude = ()

class OfficeEditForm(forms.ModelForm):
    class Meta:
        model = Office
        exclude = ('is_project', 'is_municipality')

class UserForm(UserCreationForm):
    
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
   
    password1 = forms.CharField(initial='sa2das33@dsErZZasd')
    password2 = forms.CharField(initial='sa2das33@dsErZZasd')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProjectDetailForm(forms.ModelForm):
    class Meta:
        model = ProjectDetail
        exclude = ('office',)

class MunicipalityDetailForm(forms.ModelForm):
    class Meta:
        model = MunicipalityDetail
        exclude = ('office', )
class OfficeBudgetForm(forms.ModelForm):
    class Meta:
        model = OfficeBudget
        exclude = ('office',)

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', 'email_confirmed', 'assign_date',)

users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserDetailsForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('password1', 'password2',)

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .imagecropper import PhotoForm
from django.shortcuts import render
from django.contrib.auth.models import User

from django.contrib.auth import login, authenticate
from django.views.generic import View
from .tokens import account_activation_token
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from .models import Profile
from .forms import UserDetailsForm
from userrole.forms import UserRoleForm
from userrole.mixins import LoginRequiredMixin, SuperAdminMixin, CreateView, UpdateView, DeleteView
from userrole.models import UserRole as Role, UserRole

from django.shortcuts import redirect
from django.urls import reverse_lazy

class UserRoleView(object):
    model = UserRole
    success_url = reverse_lazy('role:user-role-list')
    form_class = UserRoleForm         



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None


    if user is not None and account_activation_token.check_token(user, token):

        profile = get_object_or_404(Profile, user=uid)
        photoform = PhotoForm(request.POST or None, instance=profile)
        userform = UserDetailsForm()


        return render(request, 'profiledetails.html', {'uid': uidb64, 'photoform':photoform, 'userform':userform})
    else:
    	return redirect('users:login')

    		#return redirect('question_detail', pk=question.pk)
    	#return redirect('supa:listoffice')





def firstlogin(request, *args, **kwargs):

    if request.method=='POST':

    	password1 = request.POST.get('password1')
    	password2 = request.POST.get('password2')

    	if password2 == password1:
        	usrid = request.POST.get('uidb64')
        	uid = force_text(urlsafe_base64_decode(usrid))
        	user = User.objects.get(pk=uid)
        	user.profile.email_confirmed = True
        	user.set_password(password2)
        	user.is_active = True
        	user.save()
                office = UserRole.get_office(uid)
                profile = get_object_or_404(Profile, user=uid)
            	user1 = authenticate(username=user.username, password=password2)
            	form = PhotoForm(request.POST, request.FILES, instance=profile)

        	if form.is_valid():
        		form.save()

        	login(request, user1)

        	return redirect('office:office-dashboard', pk=office.id)
    	return redirect('error')

def my_profile(request, pk=None):
    if not pk or pk =='0':
        profile, created = Profile.objects.get_or_create(user=request.user)
        roles = request.user.user_roles.all()
    else:
        profile, created = Profile.objects.get_or_create(user__id=pk)
        roles = profile.user.user_roles.all()

    return render(request, 'users/profile.html', {'obj': profile, 'roles': roles})

office/templates/office/accountconfirm.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

office/templates/office/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

office/templates/office/office_detail.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}{{object}}{% endblock title %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      
      <ol class="breadcrumb">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i>गृह पृष्ठ</a></li>
        <li><a href="{% url 'office:office-dashboard' object.id %}"><i class="fa fa-dashboard"></i> {{office}}</a></li>

      </ol>
    </section>

 <!-- Main content -->
 <div class="col-md-12">
         

      <!-- title row -->
      <div class="row">
            <div class="col-md-3">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="{% static 'dist/img/logo.png' %}" alt="User profile picture">

              <h3 class="profile-username text-center">{{office.name}}</h3>

              <p class="text-muted text-center">जिल्ला :

                {% for district in office.district.all %}
                  {{district.district}},
                {% endfor %}</p>

              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>इ-मेल</b> <a class="pull-right">{{office.email}}</a>
                </li>
                <li class="list-group-item">
                  <b>फोन</b> <a class="pull-right">{{office.phone}}</a>
                </li>
                <li class="list-group-item">
                  <b>फ्याक्स</b> <a class="pull-right">{{office.fax}}</a>
                </li>
                <li class="list-group-item">
                  <b>कार्यालय समय</b> <a class="pull-right">{{office.office_time}}</a>
                </li>
                <li class="list-group-item">
                  <b>बिभाग</b> <a class="pull-right">{{office.department.name}}</a>
                </li>
              <li class="list-group-item">
                  <b>सेटिङ परिवर्तन</b> <a href="{% url 'reports:office-settings' office.id office.settings.id %}" %} class="pull-right">परिवर्तन गर्नुहोस्</a>
                </li>
                <li class="list-group-item">
                  <b>विवरण परिवर्तन</b> <a href="{% url 'office:office-update' office.id %}" %} class="pull-right">परिवर्तन गर्नुहोस्</a>
                </li>
              </ul>


            <!-- /.box-body -->
          </div>
          </div>
          </div>

                      <div class="col-md-9">
          
                         <div class="map-office">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1059393.3436958205!2d80.50756992099542!3d29.28690855421674!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39a1666b20c30d3d%3A0xb3a717378a19a012!2sFar-Western+Development+Region%2C+Nepal!5e0!3m2!1sen!2s!4v1498351003946"  width="100%" height="400px" frameborder="0" style="border:0" allowfullscreen></iframe>
              </div>
                      </div>

        <!-- /.col -->
      </div>
      </div>
      <!-- info row -->
      {% if office.is_municipality == True%}
       <div class="col-md-12">
          <div class="box box-solid">
           <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">थप जानकारी </h3><span class="pull-right"><a href="#" onclick="window.open(`{% url 'office:office-update-municipality' object.municipality_detail.id %}`, 'newwindow', 'width=800, height=600'); return false;">परिवर्तन गर्नुहोस्</a></span>
            </div>
      
          
<div class="col-md-6 box-solid" style="background-color: white;" >
              <dl class="dl-horizontal">

                    <b>केन्द्र : </b>{{office.municipality_detail.kendra}}<br>
                    <b>एरिया : </b>{{office.municipality_detail.area}}<br>
                    <b>वडाहरु को संख्या : </b>{{office.municipality_detail.no_of_wards}}<br>
                    <b>जनसंख्या : </b>{{office.municipality_detail.population}}<br>
              </dl>
              </div>
<div class="col-md-6 box-solid" style="background-color: white;">
              <dl class="dl-horizontal">
        
                    <b>मेयर/अध्यक्षको नाम : </b>{{office.municipality_detail.mayor_name}}<br>
                    <b>मेयर/अध्यक्षको फोन : </b>{{office.municipality_detail.mayor_phone_no}}<br>
                    <b>मेयर/अध्यक्षको ठेगाना  : </b>{{office.municipality_detail.mayor_address}}<br>
                    <b>उप-मेयर अध्यक्षको नाम : </b>{{office.municipality_detail.sub_mayor_name}}<br>
                    <b>उप-मेयर/अध्यक्षको ठेगाना : </b>{{office.municipality_detail.sub_mayor_address}}<br>
                    <b>उप-मेयर/अध्यक्षको फोन : </b>{{office.municipality_detail.sub_mayor_phone_no}}<br>
       

                    <b>वडा प्रमुखको विवरण : </b>{{office.municipality_detail.ward_chief_details}}<br>
                    <b>कृयाकलापहरु : </b>{{office.municipality_activities}}<br>
                    </dl>
                    </div>
        </div>


</div>
<br>
        {% elif office.is_project == True %}
 <div class="col-md-12">
<div class="box box-solid">
<div class="box-header with-border">
<i class="fa fa-text-width"></i>

<h3 class="box-title">थप जानकारी</h3><span class="pull-right"><a href="#" onclick="window.open(`{% url 'office:office-update-project' object.project_detail.id %}`, 'newwindow', 'width=800, height=600'); return false;">परिवर्तन गर्नुहोस्</a></span>
</div>
   <div  style="margin-left: 40px; ">
                    <b> आयोजनाको समय : </b>{{office.project_detail.project_time}}<br>
                    <b> बजेट : </b>{{office.project_detail.budget}}<br>
                    <b> बरिष्ठ इन्जिनीयर : </b>{{office.project_detail.chief_eng}}<br>
                    <b> इन्जिनीयरहरु : </b>{{office.project_detail.engineers}}<br>
      

                    <b> उद्देश्य : </b>{{office.project_detail.objective}}<br>
      </div>
</div>
</div>
        {% endif %}

        <!-- /.col -->
     
      <!-- /.row -->
        
         <!-- Table row -->
<br>


  <div class="col-md-12" style="margin-top: 10px;">
          <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">बजेटको विवरण </h3><span class="pull-right"><a href="{% url 'office:office-budget-update' office.id %}">परिवर्तन गर्नुहोस्</a></span>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <dl class="dl-horizontal">
              {% for budget in budgets %}
                 <dt>आर्थिक वर्ष:</dt> <dd>{{ budget.budget_year }}</dd>
                    <dt>बजेट      :</dt> <dd>{{ budget.budget_rs }}</dd>
                    <dt>नेपाल सरकार :</dt> <dd>{{ budget.nepalsarkar }}</dd>
                    <dt>संस्था :</dt> <dd>{{ budget.sastha }}</dd>
                    <dt>जनसंग्लनता :</dt> <dd>{{budget.anasamglanta }}</dd>
                    <dt>ऋण :</dt> <dd>{{ budget.loan }}</dd>
                    <dt>उपदान :</dt> <dd>{{ budget.upadan }}</dd>
                    <dt>दातृसंस्था :</dt> <dd>{{ budget.dritasastha }}</dd>
                    <dt>अन्तरिक :</dt> <dd>{{ budget.antarik }}</dd>
                    <dt>वैदेशिक :</dt> <dd>{{ budget.baidesikh }}</dd>
              {% endfor %}
              </dl>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
       
      <!-- /.row -->

      <!-- this row will not appear when printing -->
  <!-- /.content -->
    <div class="clearfix"></div>
  <!-- /.content-wrapper -->

{% endblock content %}

office/templates/office/office_list.html
	{% if all_offices %}
	    <h1>सम्पूर्ण कार्यालयहरु</h1>
	    <ul>
	        {% for office in all_offices %}
	       <h1>{{ office.id }}. {{ office.name }}</h1><a href="{% url 'office:office-update' office.id %}"></a>
	        {% endfor %}
	    </ul>
	{% else %}
	    <h3>कुनै कार्यालयहरु छैन</h3>
	{%endif%}

office/templates/office/success.html
<script>
if (confirm("Close Window?")) {
    close();
  }
</script>