comments/urls.py
from django.conf.urls import url


from comments.views import Comment, GetComment

app_name = 'comments'



urlpatterns = [

    url(r'^create/$', Comment.as_view(), name='comment-add'),
    url(r'^getcomment/$', GetComment.as_view(), name='comment-get'),

        ]

dcms/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from office.views import DashboardView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role")),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^notifications/', include("notifications.urls", namespace="notifications")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^$', DashboardView.as_view(), name='dashboard'),


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

office/urls.py
from django.conf.urls import url


from office.views import  OfficeAddMunicipilaty, OfficeAddProject, ProjectUpdate, MunicipalityUpdate, OfficeDetailView, \
    OfficeUserView, OfficeBudgetUpdateView

app_name = 'office'

from office.views import OfficeCreateView, AllProjectDashboard, OfficeListView, OfficeUpdateView, OfficeDeleteView, DashboardView,\
    OfficeAddOfficeHeadView, OfficeAddInfoofficerView, Monthly, OfficeDashboard, DistrictDashboard, ProfileDetailView, ProfileUpdateView, OfficeKaryakramList, DeactivateUserView



urlpatterns = [

    url(r'^office/create/$', OfficeCreateView.as_view(), name='office-add'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/$', OfficeDashboard.as_view(), name='office-dashboard'),
    url(r'^office/detail/(?P<pk>[0-9]+)/$', OfficeDetailView.as_view(), name='office-detail'),
    url(r'^office/users/(?P<pk>[0-9]+)/$', OfficeUserView.as_view(), name='office-users'),

    url(r'^district/dashbaord/(?P<pk>[0-9]+)/$', DistrictDashboard.as_view(), name='district-dashboard'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/karyakramlist/$', OfficeKaryakramList.as_view(), name='office-karyakram-list'),
    url(r'^office/update/(?P<pk>[0-9]+)/$', OfficeUpdateView.as_view(), name='office-update'),
    url(r'^office/delete/(?P<pk>[0-9]+)/$', OfficeDeleteView.as_view(), name='office-delete'),
    url(r'^office/list/$', OfficeListView.as_view(), name='office-list'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addofficehead/$', OfficeAddOfficeHeadView.as_view(), name='office-add-office-head'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addinfoofficer/$', OfficeAddInfoofficerView.as_view(), name='office-add-info-officer'),
    #url(r'^office/(?P<pk>[0-9]+)/addtype/$', OfficeAddUserView.as_view(), name='office-addtype'),
    url(r'^office/(?P<pk>[0-9]+)/addmunicipality/$', OfficeAddMunicipilaty.as_view(), name='office-add-municipilaty'),
    url(r'^office/(?P<pk>[0-9]+)/addproject/$', OfficeAddProject.as_view(), name='office-add-project'),
    url(r'^office/(?P<pk>[0-9]+)/updateproject/$', ProjectUpdate.as_view(), name='office-update-project'),
    url(r'^office/(?P<pk>[0-9]+)/updatemunicipality/$', MunicipalityUpdate.as_view(), name='office-update-municipality'),
    
    url(r'^office/addbudget/(?P<pk>[0-9]+)/$', OfficeBudgetUpdateView.as_view(), name='office-budget-update'),
    url(r'^deactivate_user/$', ProfileUpdateView.as_view(), name='deactivate-users'),
    url(r'^office/users/profile_update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^office/users/profile_detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='profile-detail'),
    url(r'^office/monthly/$', Monthly.as_view(), name='monthly-report'),
    url(r'^allprojects/$', AllProjectDashboard.as_view(), name='all-projects'),
    

        ]

reports/urls.py
from django.conf.urls import url


from .views import KaryakramCreateView, KaryakramUpdateView, LakxyaCreateView, PragatiCreateView, KaryakramListView, \
    ReportView, KaryakramControlList, YearlyControlList, FirstControlList, SecondControlList, ChildKaryakramCreateView, \
    OfficeSettings, FilesSubmitted, MonthlyControlList, MonthlyProgressList, MonthlyProgressDetail, MonthlyProgressCreateView

app_name = 'reports'

urlpatterns = [
    url(r'^karyakram/list/(?P<office>[0-9]+)/$', KaryakramListView.as_view(), name='karyakram-list'),
    url(r'^office/settings/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', OfficeSettings.as_view(), name='office-settings'),
    url(r'^karyakram/controllist/(?P<office>[0-9]+)/$', KaryakramControlList.as_view(), name='karyakram-control-list'),
    url(r'^karyakram/yearlycontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', YearlyControlList.as_view(), name='yearly-control-list'),
    url(r'^karyakram/firstcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', FirstControlList.as_view(), name='first-control-list'),
    url(r'^karyakram/secondcontrollist/(?P<office>[0-9]+)/(?P<type>[0-9]+)/$', SecondControlList.as_view(), name='second-control-list'),
    url(r'^karyakram/create/(?P<office>[0-9]+)/$', KaryakramCreateView.as_view(), name='karyakram-add'),
    url(r'^karyakram/create/child/(?P<office>[0-9]+)/(?P<karyakram>[0-9]+)/$', ChildKaryakramCreateView.as_view(), name='karyakram-add-child'),
    url(r'^list/(?P<office>[0-9]+)/(?P<awadhi>[0-9]+)/$', ReportView.as_view(), name='reports'),
    url(r'^karyakram/update/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', KaryakramUpdateView.as_view(), name='karyakram-update'),
    url(r'^karyakram/addlaksya/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', LakxyaCreateView.as_view(), name='add-lakxya'),
    url(r'^karyakram/addpragati/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<awadhi>[0-9]+)/$', PragatiCreateView.as_view(), name='add-pragati'),
    url(r'^karyakram/filessubmited/(?P<office>[0-9]+)/$', FilesSubmitted.as_view(), name='files-submited'),
    url(r'^karyakram/monthlylist/(?P<office>[0-9]+)/$', MonthlyControlList.as_view(), name='monthly-control-list'),
    url(r'^karyakram/monthlyallprogresslist/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/$', MonthlyProgressList.as_view(), name='monthly-all-progress-list'),
    url(r'^karyakram/addmonthlypragati/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<month_id>[0-9]+)/$', MonthlyProgressCreateView.as_view(), name='add-monthly-pragati'),
    url(r'^karyakram/monthlyprogressdetail/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/$', MonthlyProgressDetail.as_view(), name='monthly-progress-detail'),    

        ]

reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, ListView, TemplateView

from office.models import Office
from reports.forms import KaryakramForm, LakxyaForm, PragatiForm, ChildKaryakramForm, OfficeSettingsForm, MonthlyProgressForm
from reports.models import KaryaKram, Lakxya, Pragati, OfficeSetting
from userrole.mixins import CreateView, OfficeView, OfficerMixin, UpdateView
from django.views.generic.edit import CreateView as BaseCreateView
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.db.models import Prefetch
from .models import MonthlyProgress, Months
from .npdateconverter import NepaliDateConverter
from django.contrib import messages
from django.contrib.auth.models import User
from notifications.signals import notify
from channels import Group
import json

class KaryakramView(object):
    model = KaryaKram
    form_class = KaryakramForm


class LakxyaView(object):
    model = Lakxya
    form_class = LakxyaForm


class PragatiView(object):
    model = Pragati
    form_class = PragatiForm


class OfficeSettingView(object):
    model = OfficeSetting
    form_class = OfficeSettingsForm


class MonthlyProgressView(object):
    model = MonthlyProgress
    form_class = MonthlyProgressForm


class OfficeSettings(OfficeView, OfficerMixin, OfficeSettingView, UpdateView):
    def get_success_url(self):
        return reverse('office:office-detail', args=(self.kwargs.get('office'),))


class KaryakramCreateView(OfficeView, KaryakramView, CreateView):
    def get_context_data(self, **kwargs):
        data = super(KaryakramCreateView, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        return data

    def get_success_url(self):
        return reverse('reports:karyakram-control-list', args=(self.object.office.id,))


class ChildKaryakramCreateView(OfficeView, KaryakramView, CreateView):
    form_class = ChildKaryakramForm
    def get_context_data(self, **kwargs):
        data = super(ChildKaryakramCreateView, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        return data
    form_class = ChildKaryakramForm

    def form_valid(self, form):
        super(ChildKaryakramCreateView, self).form_valid(form)
        form.instance.karyakram = KaryaKram.objects.get(pk=self.kwargs.get('karyakram'),)
        self.object = form.save()
        return redirect(reverse('reports:add-lakxya', args=(self.object.office.id, self.object.id, 0)))

    def get_success_url(self):
        return reverse('reports:add-lakxya', args=(self.object.office.id, self.object.id, 0))

class KaryakramUpdateView(OfficeView, KaryakramView, UpdateView):

    def get_success_url(self):
        return reverse('office:office-dashboard',args=(self.object.office.id,))

class KaryakramListView(OfficeView, KaryakramView, OfficerMixin, ListView):
    def get_context_data(self, **kwargs):
        data = super(KaryakramListView, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        return data


class LakxyaCreateView(OfficeView, LakxyaView, FormView):
    template_name = 'reports/lakxya_form.html'

    def get_context_data(self, **kwargs):
        data = super(LakxyaCreateView, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        return data


    def get(self, request, *args, **kwargs):
        awadhi = self.kwargs['awadhi']
        karyakram_id = self.kwargs['karyakram_id']
        karyakram = KaryaKram.objects.get(pk=karyakram_id)

        if awadhi == '1' and not Lakxya.objects.filter(karyakram=karyakram_id, awadhi=0):
            return redirect(reverse('reports:add-lakxya',args=(karyakram.office.id, karyakram_id, 0)))
        if awadhi == '2' and not Pragati.objects.filter(karyakram=karyakram_id, awadhi=1):
            return redirect(reverse('reports:add-pragati',args=(karyakram.office.id, karyakram_id, 1)))

        laxya, created = Lakxya.objects.get_or_create(karyakram=karyakram, fiscal_year_id=1, awadhi=awadhi)
        form = LakxyaForm(instance=laxya)
        return render(request, 'reports/lakxya_form.html', {'form': form,'awadhi': awadhi, 'karyakram':karyakram},)


    def form_valid(self, form):
        lakxya = Lakxya.objects.get(pk=form.data.get('lakxya'))
        lakxya.paridam = form.cleaned_data['paridam']
        lakxya.var = form.cleaned_data['var']
        lakxya.budget = form.cleaned_data['budget']
        lakxya.save()
        # correct url to redirect after lakxya save and fill pragati
        
        messages.success(self.request, 'Lakxya Sucessfully Added.')
        if self.request.group.id == 4:
            recipients = User.objects.filter(user_roles__group__name="Office Head", user_roles__office__id=1)
            group = "office_head-"+str(1)
        else:
            recipients = User.objects.filter(user_roles__group__name="Information Officer")
            # recipients = User.objects.filter(user_roles__group__name="Information Officer", user_roles__office__id=self.request.office.id)

            group = "info_officer-"+str(1)
        
        notify.send(self.request.user, recipient=recipients, verb='Updated new Lakshya', action_object=lakxya, detail_url = '/comment/add/22/')

        Group("%s" % group).send({
            'text': json.dumps({
                'by': str(self.request.user),
                'verb': "commented on",
                'time':"Just Now",
                'detail_url':"/comment/add/22/",
                'action_object':str(lakxya),
            })
        })

        if lakxya.awadhi == 1:
            return redirect(reverse('reports:first-control-list',args=(lakxya.karyakram.office.id, 0,)))
        elif lakxya.awadhi == 2:
            return redirect(reverse('reports:second-control-list',args=(lakxya.karyakram.office.id, 0,)))
        elif lakxya.awadhi == 0:
            return redirect(reverse('reports:yearly-control-list',args=(lakxya.karyakram.office.id, 0,)))
        else:
            return redirect(reverse('office:office-dashboard',args=(lakxya.karyakram.office.id,)))


        #if lakxya.awadhi == 0:
        #     return redirect(reverse('reports:add-laksya',args=(lakxya.karyakram.office.id, lakxya.karyakram.id, 1)))
        # else:
        #return redirect(reverse('office:office-dashboard',args=(lakxya.karyakram.office.id,)))
    def sendrealtimenotif(group, byuser, url, action_object, verb):
        Group("%s" % group).send({
            'text': json.dumps({
                'by': str(byuser),
                'verb': str(verb),
                'time':"Just Now",
                'detail_url':str(url),
                'action_object':str(action_object),
            })
        })

# class PragatiCreateView(OfficeView, PragatiView, UpdateView):        
#     def dispatch(self, request, *args, **kwargs):
#         awadhi = self.kwargs['awadhi']
#         karyakram_id = self.kwargs['karyakram_id']
#         karyakram = KaryaKram.objects.get(pk=karyakram_id)
#         if awadhi == '1' and not Lakxya.objects.filter(karyakram=karyakram_id, awadhi=1):
#             return redirect(reverse('reports:add-lakxya',args=(karyakram.office.id, karyakram_id, 1)))
#         if awadhi == '2' and not Lakxya.objects.filter(karyakram=karyakram_id, awadhi=2):
#             return redirect(reverse('reports:add-lakxya',args=(karyakram.office.id, karyakram_id, 2)))
#         if awadhi == '0' and not Pragati.objects.filter(karyakram=karyakram_id, awadhi=2):
#             return redirect(reverse('reports:add-pragati',args=(karyakram.office.id, karyakram_id, 2)))
#         else:
#             return super(PragatiCreateView, self).dispatch(request, *args, **kwargs)
#     def get_object(self):
#         awadhi = self.kwargs['awadhi']
#         karyakram_id = self.kwargs['karyakram_id']
#         karyakram = KaryaKram.objects.get(pk=karyakram_id)
       
#         pragati, created = Pragati.objects.get_or_create(karyakram=karyakram, fiscal_year_id=1, awadhi=awadhi)

#         return pragati


#     def get_success_url(self):



#         if self.request.group.id == 4:
#             recipients = User.objects.filter(user_roles__group__name="Office Head", user_roles__office__id=1)
#             group = "office_head-"+str(1)
#         else:
#             recipients = User.objects.filter(user_roles__group__name="Information Officer", user_roles__office__id=1)
#             group = "info_officer-"+str(1)
        
#         notify.send(self.request.user, recipient=recipients, verb='updated pragati', action_object=self.object, detail_url = '/comment/add/22/')

      

#         if self.object.awadhi == 1:
#             return reverse('reports:first-control-list',args=(self.object.karyakram.office.id, 1))
#         elif self.object.awadhi == 2:
#             return reverse('reports:second-control-list',args=(self.object.karyakram.office.id, 1))
#         elif self.object.awadhi == 0:
#             return reverse('reports:yearly-control-list',args=(self.object.karyakram.office.id, 1))
#         else:
#             return reverse('office:office-dashboard',args=(self.object.karyakram.office.id,))

        
      
class PragatiCreateView(OfficeView, PragatiView, CreateView):
    def get(self, request, *args,  **kwargs):
        awadhi = self.kwargs['awadhi']
        karyakram_id = self.kwargs['karyakram_id']
        karyakram = KaryaKram.objects.get(pk=karyakram_id)

        if awadhi == '1' and not Lakxya.objects.filter(karyakram=karyakram_id, awadhi=1):
            return redirect(reverse('reports:add-lakxya',args=(karyakram.office.id, karyakram_id, 1)))
        if awadhi == '2' and not Lakxya.objects.filter(karyakram=karyakram_id, awadhi=2):

templates/reports/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

templates/reports/karyakram_control.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}कार्यक्रम{% endblock title %}

  
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}"> 
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css"> 
  <style type="text/css">                                              
  #div2 {
    white-space: nowrap;
    width: 20em;
    overflow: hidden;
    text-overflow: ellipsis;

}</style>

{% endblock extra_css %}

{% block content %}
 <section class="content-header">
      <ol class="breadcrumb">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i>गृह पृष्ठ</a></li>
        
         <li><a href="{% url 'office:office-dashboard' office %}"><i class="fa fa-dashboard"></i>{{ office_obj.name }}</a></li>
       
      </ol>
    </section>
    <!-- bread crumb  -->

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-body">

        <div class="pratham-lakchya">
          
 
    <h2>सम्पूर्ण कार्यक्रमहरु <a href="{% url 'reports:karyakram-add' office %}"></h2>
        <i class="fa fa-plus-circle" aria-hidden="true">  मूल कार्यक्रम थप्नुहोस्</i></a>
        <br>
          

          <table id = "datatable" class="table table-bordered text-center">
            <thead>
            <tr>
              <th rowspan="2">सि.नं.</th>
              <th rowspan="2"><div id="div2">नाम</div></th>
              <th rowspan="2">युनिट</th>
              <th rowspan="2">कोड</th>
              <th rowspan="2">क्रियाकलाप</th>
              <th colspan="3">बार्षिक लक्छ्य</th>
              
              
              <th rowspan="2">थप्नुहोस्</th>
            </tr>
            <tr>
              <th>परिमाण</th>
              <th>भार</th>
              <th>बजेट</th>

              
            
            </tr>
            </thead>
            <tbody>
              
                    {% for karyakram in object_list %}
                    <tr style="background-color: #ededed;">
                       <th>{{ karyakram.id }}</th>
                       <th>{{ karyakram.name }}</th>
                       <th></th>
                       <th></th>
                       <th></th>
                       <th></th>
                       <th></th>
                       <th></th>
                 
                       <td>

                       <a href="{% url 'reports:karyakram-add-child' karyakram.office.id karyakram.id %}"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>

                       </td>

                       
                       <!-- <td>{{ karyakram.parent.all.0.id }}</td> -->

                       
                    </tr>
                    {% if karyakram.childs %}
                          {% for subkaryakrams in karyakram.childs %}
                            
                            <tr>
                            <td><span class="glyphicon glyphicon-arrow-right"></span> {{ subkaryakrams.karyakram.id }}.{{ forloop.counter }}</td>
                                <td>{{ subkaryakrams.name }}</td>
                             <td>{{ subkaryakrams.unit }}</td>
                             <td>{{ subkaryakrams.code }}</td>
                             <td>{{ subkaryakrams.kriyakalap }}</td>
                             
                             {% for sub in subkaryakrams.get_yearly_lakxya.all|slice:":1" %}
                             <td>{{ sub.paridam }}</td>
                             <td>{{ sub.var }}</td>
                             <td>{{ sub.budget }}</td>
                             {% endfor %}
                             <td></td>
                             
                             
                            </tr> 

                          {% endfor %}

                       {% endif %}
                    {% endfor %}
                    
                   
                




            </tbody>
            
            
          </table>
        </div>

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>

 
{% endblock content %}


{% block extra_script %}
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script>
  $(function () {
    $("#datatable").DataTable(
      {
        scrollX: true,
        dom: 'Bfrtip',
        lengthMenu: [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
        buttons: [
            'pageLength','copy', 'csv', 'excel', 'pdf', 'print',
        ]
      });
    });
</script>
{% endblock extra_script %}

templates/reports/monthly_control.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}कार्यक्रम{% endblock title %}

  
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}"> 
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css"> 
  <style type="text/css">                                              
  #div2 {
    white-space: nowrap;
    width: 20em;
    overflow: hidden;
    text-overflow: ellipsis;

}</style>

{% endblock extra_css %}

{% block content %}
 <section class="content-header">
      <ol class="breadcrumb">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i>गृह पृष्ठ</a></li>
        
         <li><a href="{% url 'office:office-dashboard' office %}"><i class="fa fa-dashboard"></i>{{ office_obj.name }}</a></li>
       
      </ol>
    </section>
    <!-- bread crumb  -->

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-body">

        <div class="pratham-lakchya">
          
 
    <h2>सम्पूर्ण कार्यक्रमहरु </h2>
        <br>
          

         <table id="datatable" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>क्र. म.</th>
								<th>कार्य विवरण</th>
								<th>महिना</th>
								<th>महिनाको प्रगती</th>
								<th>हाल सम्मको प्रगती</th>
								<th>कैफियत</th>
								<th>थप्नुहोस</th>
							</tr>
							
						</thead>
						<tbody>
                        {% for karyakram in object_list %}

							<tr>
								<td>{{ karyakram.id }}</td>
								<td>{{ karyakram.name }}</td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
                             {% if karyakram.childs %}
                                 {% for subkaryakrams in karyakram.childs %}

                                    <tr>
                                    <td><span class="glyphicon glyphicon-arrow-right"></span> {{ subkaryakrams.karyakram.id }}.{{ forloop.counter }}</td>
                                        <td>{{ subkaryakrams.name }}</td>

                                        {% for monthlydata in subkaryakrams.get_monthly_progress.all|slice:":1" %}
                                        <td>{{ monthlydata.month }}</td>
                                        <td>{{ monthlydata.pragati }}</td>
                                        <td><a href="{% url 'reports:monthly-progress-detail' karyakram.office.id subkaryakrams.id %}" title="" class="btn btn-xs btn-primary"></i>हाल सम्मको प्रगती</a></td>
                                        <td>{{ monthlydata.comments }}</td>
                                        {% empty %}
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        {% endfor %}
                                        
                                        <td><a href="{% url 'reports:monthly-all-progress-list' karyakram.office.id subkaryakrams.id %}" title="" class="btn btn-xs btn-primary"><i class="fa fa-plus"></i></a></td>
                                         
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}


						</tbody>
					</table>
        </div>

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </section>

 
{% endblock content %}


{% block extra_script %}
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script>
  $(function () {
    $("#datatable").DataTable(
      {
        scrollX: true,
        dom: 'Bfrtip',
        lengthMenu: [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
        buttons: [
            'pageLength','copy', 'csv', 'excel', 'pdf', 'print',
        ]
      });
    });
</script>
{% endblock extra_script %}

templates/reports/officesetting_form.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}आर्थिक वर्ष परिवर्तन गर्नुहोस्{% endblock title %}

{% block content %}
<form class = "" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
	{% include 'reports/form_template.html' %}


	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">पेश गर्नुहोस्</button>
		</div>
	</div>

</form>
{% endblock content %}